# Generated by Django 4.1.2 on 2022-11-13 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='id_chat',
            new_name='chat',
        ),
    ]
